# Generated by Django 5.1.2 on 2024-10-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('city', models.CharField(db_column='city', max_length=10)),
                ('street', models.CharField(db_column='street', max_length=10)),
                ('contact', models.CharField(db_column='contact', max_length=10)),
            ],
            options={
                'db_table': 'parts',
            },
        ),
    ]
