# Generated by Django 5.1.2 on 2024-12-06 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_handling',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
